name: CI

on: [push, fork, pull_request, workflow_dispatch]

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@master

  test:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
      fail-fast: false
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.12
          enable-cache: true
          cache-dependency-glob: pyproject.toml
      - name: Install dependencies
        run: |
          uv export --no-hashes --group test --no-dev | uv pip install -r -
      - name: Run tests
        run: pytest -v -s

  check:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
      fail-fast: false
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.12
          enable-cache: true
          cache-dependency-glob: pyproject.toml
      - name: Install dependencies
        run: |
          uv export --no-hashes | uv pip install -r - basedpyright
      - name: Check code quality
        run: |
          ruff format --check --diff
          ruff check --diff
      - name: Type Check
        run: |
          basedpyright
